function I = simpcomp(a,b,N,fun)
    H = (b-a)/N;
    x = a:H/2:b;
    y = fun(x);
    I = ( H / 6 ) * ( y( 1 ) + ...
        2 * sum( y( 3 : 2 : 2 * N - 1 ) ) + ...
        4 * sum( y( 2 : 2 : 2 * N ) ) + ...
        y( 2 * N + 1 ) );
