function[A] = pentadiag(d,b,a,c,e,n)

%Crea una matrice pentadiagonale nxn con "a" principale, "b" sotto, "c"
%sopra "d" sotto sotto, "e" sopra sopra

A = diag(a*ones(1,n)) + ...
	diag(b*ones(1,n-1),-1) + ...
	diag(d*ones(1,n-2),-2) + ...
	diag(c*ones(1,n-1),1) + ...
	diag(e*ones(1,n-2),2);
end